services:
  postgres:
    container_name: postgres
    image: postgres:17.5
#    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
    networks:
      - aws-net

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - minio-batch-data:/data
    command: server /data --console-address ":9001"
    networks:
      - aws-net

volumes:
  minio-batch-data:

networks:
  aws-net: