spring:
  application:
    name: spring-batch-aws-telemetry
  cloud:
    aws:
      s3:
        endpoint: ${MINIO_URL}
        region: af-south-1
        path-style-access-enabled: true
        bucket: sales-info # prop is custom
      credentials:
        access-key: ${MINIO_ACCESS_KEY}
        secret-key: ${MINIO_SECRET_KEY}
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  datasource:
    username: root
    password: root
    url: ${DB_URL}
  jpa:
    hibernate:
      ddl-auto: create

